const Discord = module.require("discord.js");

module.exports = {
  name: "roast",
  description: "Roasts a user",
  run: async (client, message, args) => {
    let target = message.mentions.members.first() || args.join(" ");
    let isBotOwner = require("../../config.json").OWNER_ID;
    if (args.length == 0) {
      return message.channel
        .send("Damn, You are trying to roast the air..??")
        .then((msg) => setTimeout(() => msg.delete(), 2300));
    }
    var roasts = [
      "*Steckt dich in den Ofen.*",
      "Du bist so dumm.",
      "Entschuldigung, ich kann dich nicht hören, wie nervig du bist.",
      "Ich habe Besseres zu tun.",
      "Du bist so dumm wie Cleverbot.",
      "Dein IQ ist niedriger als der Marianengraben.",
      "Du bist so nervig, sogar die Fliegen halten sich von deinem Gestank fern.",
      "Geh bitte weg.",
      "Ich würde dir einen bösen Blick zuwerfen, aber du hast schon einen.",
      "Es sieht so aus, als hätte dein Gesicht Feuer gefangen und jemand hat versucht, es mit einem Hammer zu löschen.",
      "Dein Stammbaum muss ein Kaktus sein, denn jeder darauf ist ein Arschloch.",
      "Eines Tages wirst du weit kommen, und ich hoffe, du bleibst dort.",
      "Der Zoo hat angerufen. Sie fragen sich, wie du aus deinem Käfig gekommen bist.",
      "Ich hatte auf einen Geisteskampf gehofft, aber du scheinst unbewaffnet zu sein.",
      "Sie sind der Beweis dafür, dass die Evolution auch umgekehrt gehen kann.",
      "Gehirne sind nicht alles, in deinem Fall sind sie nichts.",
      "Tut mir leid, dass ich das nicht verstanden habe, ich spreche keinen Idioten.",
      "Warum ist es akzeptabel für dich ein Idiot zu sein, aber nicht für mich, darauf hinzuweisen?",
      "Wir sind alle von Affen abstammen, aber du bist nicht weit genug gesprungen.",
      "Selbst Affen können in den Weltraum fliegen, da fehlt dir eindeutig ein gewisses Potenzial.",
      "Es ist Kopf über Muskelkraft, doch du hast keines davon.",
      "Du siehst aus wie ein Affe und du riechst auch so.",
      "Selbst unter Idioten fehlt dir.",
      "Du scheiterst auch dann, wenn du absolut nichts tust.",
      "Wenn es eine Stimme für 'geringste Erfolgsaussicht' gäbe, würdest du den ersten Preis gewinnen.",
      "Ich bin von Idioten umgeben... Oder warte, das bist nur du.",
      "Ich will nach Hause. Naja, wirklich, ich will nur weg von dem schrecklichen Geruch, den du da hast.",
      "Jedes Mal, wenn du mich berührst, muss ich nach Hause gehen und alle meine Klamotten neunmal waschen, nur um wieder einen normalen Geruch zu bekommen.",
      "Wenn ich einen Dollar für jedes Gehirn hätte, das du nicht hast, hätte ich einen Dollar.",
      "Ich würde dir helfen, erfolgreich zu sein, aber du bist unfähig.",
      "Ihr Haaransatz ist wie ein Diagramm aufgebaut, positive und negative Kräfte ziehen sich an, aber die Haarschneidemaschine und Ihr Haar stoßen ab.",
      "Ich kenne einen guten Witz! Du!",
      "Du hast zwei Teile deines Gehirns, 'links' und 'rechts'. Auf der linken Seite ist nichts richtig. Auf der rechten Seite ist nichts mehr übrig.",
      "Ist dein Arsch eifersüchtig auf die Menge Scheiße, die gerade aus deinem Mund gekommen ist?",
      "Ich führe keinen mentalen Kampf mit Unbewaffneten.",
      "Zwei Fehler machen kein Recht, nimm deine Eltern als Beispiel.",
      "Deine Geburtsurkunde ist ein Entschuldigungsbrief der Kondomfabrik.",
      "Du klingst vernünftig. Es muss Zeit sein, meine Medikamente zu erhöhen!",
      "Du musst auf einer Autobahn geboren worden sein, denn dort passieren die meisten Unfälle.",
      "Du bist so hässlich, als deine Mutter dich in der Schule abgesetzt hat, hat sie eine Geldstrafe dafür bekommen.",
      "Wenn Lachen die beste Medizin ist, muss dein Gesicht die Welt heilen.",
      "Ich würde die Dinge gerne aus deiner Sicht sehen, aber ich scheine meinen Kopf nicht so weit in den Arsch zu kriegen.",
      "Die einzige Möglichkeit, jemals flachgelegt zu werden, besteht darin, in einen Hühnerarsch zu kriechen und zu warten.",
      "Ich bin neidisch auf all die Leute, die dich noch nicht kennengelernt haben!",
      "Wenn ich ein Gesicht wie deins hätte, würde ich meine Eltern verklagen.",
      "Es gibt nur ein Problem mit deinem Gesicht. Ich kann es sehen.",
      "Liebst du die Natur nicht, trotz allem, was sie dir angetan hat?",
      "Welche Sprache sprichst du? Weil es sich nach Quatsch anhört.",
      "Dummheit ist kein Verbrechen, also kannst du gehen.",
      "Also ist dir ein Gedanke in den Sinn gekommen? Muss eine lange und einsame Reise gewesen sein.",
      "Sie haben einen Raumtemperatur-IQ - wenn der Raum in der Antarktis liegt.",
      "Wenn du wirklich von Fehlern wissen willst, solltest du deine Eltern fragen.",
      "Ich würde dich fragen, wie alt du bist, aber ich weiß, dass du nicht so hoch rechnen kannst.",
      "Willst du wissen, wie ich all diese Beleidigungen bekomme? Ich benutze etwas namens Intelligenz.",
      "Ich wollte dir einen bösen Blick zuwerfen, aber du hast schon einen.",
      "Ich weiß nicht, was dein Problem ist, aber ich wette, es ist schwer auszusprechen.",
      "Gehirne sind nicht alles. In deinem Fall sind sie nichts.",
      "Was halten Sie als Außenstehender von der Menschheit?",
      "Du siehst aus wie ein Vorher-Bild.",
      "Oh, was? Entschuldigung. Ich habe versucht, dir eine Persönlichkeit vorzustellen.",
      "Du bist der Grund, warum der Genpool einen Rettungsschwimmer braucht.",
      "Wir können immer erkennen, wann du lügst. Deine Lippen bewegen sich.",
      "Vielleicht kaufe ich gerne ein, aber ich kaufe nicht deinen Blödsinn.",
      "Die Hölle ist übersät mit all deinen gelöschten Selfies.",
      "Du bist der lebende Beweis dafür, dass Dung Beine sprießen und gehen kann.",
      "Ist dir klar, dass Make-up deine Dummheit nicht beheben wird?",
      "Dich einen Idioten zu nennen wäre eine Beleidigung für alle dummen Leute.",
      "Du hast das perfekte Gesicht fürs Radio.",
      "Aww, es ist so süß, wenn du versuchst, über Dinge zu reden, die du nicht verstehst.",
      "Wenn ich von einem Arschloch hören wollte, würde ich furzen.",
      "Was ist der Unterschied zwischen dir und einem Ei? Eier werden gelegt!",
      "Du siehst aus wie ein Stein, der in einen Sandhaufen zerschmettert, zu einem Stumpf gerollt und durch einen Asthma-Inhalator geraucht wurde.",
      "Ihr Rat ist ungefähr so ​​nützlich wie ein Luftschutzbunker aus Pappmaché.",
      "Ist es traurig, dass dein Titelsong genauso gut eine 0/0-Signatur haben könnte?",
      "Du bist so fett, du lässt die Galaxie so aussehen, als ob sie auf molekularer Ebene wäre.",
    ];
    await message.channel.send(
      `${target}, ${roasts[Math.floor(Math.random() * roasts.length)]}`
    );
  },
};
